language: c
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created via the "travis encrypt" command using the project repo's public key
    - secure: "DEyIWf0/gl5/OqjTR/k8PXeY6zoju377Z/3YHTG5lOie5OPMo0KglvX5qLjf46jAJ1wu5o3+urAeChAyxskIIPA8r+1y1UtjIlKwNvAUhMlNUGy1F0JU94P1vIfQxTlcB2klcSWvDzyke++kSAqtkrZmoSfs8v6lKri6T7pkdJ9Yd/j8qIcdU5RMt+Cn0oYHszZ8h1Fkz72XAbEddJ3pN7a8cyxFnRm03Tz3dzlONJ14CSMaquoEUZp/rS5HFL0KGZiGkQ6rE5ZwTGVnSnYVTN9azbaOEPmImcxIUsNxQiJTA4yzPPw94A/AufOjYqoMXY4HTU2tMp+QNR1QHKuKLSR+V1AHCz9YMbqxQqgcnbOmKIybVPaFOLNos4Fu4o8hvN8kINqQWlatvQPfzwChqGBRuXBwlI6lRfesQLa2nrqtu9mKx6LNhzc6pt0cH2HyQOemjfu1uYMY7ZY3FL+LPtyfFk48NoU6hZziKHrkRomtDrcKIks31mHi8/qPBchLHqUV4zdQyTGgYr2LLPt3UG9QMkM+sW5TKBIypn2CcVk3dMUTS1QWp4aiPC/JfvVGneUp/6dQyxpXoFj3p8sxDOYGr67fFRlM/jqSH0uw/C0tLSQmy0ThqzijqOk3P7QzlCNn96o4sMt42n2Ys1KV2DaldikiVhq37Msl17UCtc0="
    - COVERITY_SCAN_PROJECT_NAME="grover/uMDNS"
    - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="michael.ruck@michaelruck.de"
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND="mkdir -p build && cd $_ && cmake .."
    - COVERITY_SCAN_BUILD_COMMAND="mkdir -p build && cd $_ && cmake .."
matrix:
 include:
    - os: osx
      compiler: clang
      osx_image: xcode8.1
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
addons:
  apt:
    sources:
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
    - cmake
    - cmake-data
    - doxygen
    - graphviz
sudo: required
before_install:
- "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
- "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install cmake; fi"
- "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install doxygen; fi"
- "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install graphviz; fi"
- 'if [[ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_BRANCH}" == "coverity_scan" ]]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne "/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p" | sudo tee -a /etc/ssl/certs/ca-; fi'
- 'if [[ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_BRANCH}" == "coverity_scan" && "${TRAVIS_JOB_NUMBER##*.}" == "3" ]]; then curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | bash || true ; fi'
script:
- mkdir -p build && cd $_
- cmake --version
- cmake .. && make
- tests/unit/uMDNSUnitTests
- cd ..
- mkdir -p apidoc
- doxygen Doxyfile
