site_name: uMDNS
site_url: http://umdns.readthedocs.io/
site_description: uMDNS - an MDNS responder for connected microcontrollers
site_author: Michael Fr&ouml;hlich

repo_url: https://github.com/grover/uMDNS

pages:
- Home: index.md
- User Guide:
  - Building: Building.md
  - Supported resource record types: Supported resource record types.md
- Developing:
  - Contributing: CONTRIBUTING.md
  - Contributors: CONTRIBUTORS.md
- License: LICENSE.md

copyright: Copyright &copy; 2016 by Michael Fr&ouml;hlich
